### PR TITLE
Translation : Korean

### PR DESCRIPTION
**Pull request by joonas-yoon**
New pull request and repo instead of Translation : Korean(#118) because linked repo in #118 is broken(or changed to private or deleted).

And issue is reopened. So, i made some stuffs and i will more.
also i have some important works for **synchronizing** with texts **in current master branch.**

If anyone who want to join, fork [**this repository**](https://github.com/joonas-yoon/coding-interview-university/tree/master) please.

ans this comment for who can speak korean:
그리고 번역투를 자연스러운 한국어 문장으로 변경하는 것에 대해 의견을 구하고 싶습니다.
ex) `행운을 빈다!` -> `행운을 빕니다!`

### CODE REVIEW

**Comment by joonas-yoon** [comment]
I'm using diff tool to sync files by [mergely.com](http://www.mergely.com/editor). I hope it helps you.

**Comment by jwasham** [comment]
Thank you!

**Comment by joonas-yoon** [comment]
You can merge this PL, but I hope it will not to be closed.

**Comment by jwasham** [comment]
Thank you. Well, it closed the pull request, but you can open another. I don't think I can reopen it now that it's merged.

**Pull request merged**
