### PR TITLE
Persian translation added

### PR DESCRIPTION
**Pull request by develhopper**
The first parts of the document were translated

### CODE REVIEW

**Comment by jwasham** [comment]
Thank you. Do you want me to pull this now or wait?

**Comment by develhopper** [comment]
No hurry, you can pull when the translation is complete
I think the translation will be finished by next week

**Comment by develhopper** [comment]
Hi, most of the sections were translated, some of the sections contained specialized terms that I could not find alternative terms in Persian.
You can pull now if its OK

**Comment by jwasham** [comment]
Thanks for the hard work!

**Pull request merged**
