### PR TITLE
Add Binary Heaps MIT into Heap Part

### PR DESCRIPTION
**Pull request by zerone0x**

### CODE REVIEW

**Comment by zerone0x** [comment]
Hi @jwasham I found the latest MIT 6.006 video on heaps. I believe it could be helpful for others. Could you please review it? Thank you in advance!

**Comment by jwasham** [comment]
Thanks for this. Please replace the older MIT video (the one above it) with this one.

**Comment by zerone0x** [comment]
NP! Already replaced.

**Comment by jwasham** [comment]
Thank you!

**Pull request merged**
