### PR TITLE
Added Pramp, a platform to practice interviews

### PR DESCRIPTION
**Pull request by meshuamam**
* Added in English, Hebrew and where minor translations weren't made (Arabic, Spanish, French, etc.)
* Fixed a typo in Hebrew in the word 'search'
* Fixed link to Interview Process & General Interview Prep in Hebrew

### CODE REVIEW

**Comment by jwasham** [comment]
Thanks. Pramp is already included in the mock interviews section.

**Comment by meshuamam** [comment]
@jwasham Thanks, I totally missed it.
I fixed the duplication, moved it to the right places in some languages, and added the relevant Hebrew translation.

**Comment by jwasham** [comment]
Please remove referral codes.

**Comment by meshuamam** [comment]
I may have not explain them correctly. These are codes for analytical
purposes, not promotion/referral promotions (I'm one of Pramp's
co-founders).
If that's not ok with you, I'll of course remove them.

**Comment by meshuamam** [comment]
@jwasham is that ok with you or would you like me to remove them?

**Comment by jwasham** [comment]
Yes, please remove them. I'd suggest looking at referrers in Google analytics for this case.

I don't want to give the impression that this is a money-making venture.

**Comment by meshuamam** [comment]
Removed everything but the translation fixes/additions.

**Comment by jwasham** [comment]
Thanks!

**Pull request merged**
