### PR TITLE
fix action error

### PR DESCRIPTION
**Pull request by tianheg**

### CODE REVIEW

**Comment by jwasham** [comment]
Hopefully this will fix the issues. Thank you!

**Comment by tianheg** [comment]
I tried times, still error([source](https://github.com/rbew/coding-interview-university/actions/runs/2255195043)):

```sh
You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 24 MB
```

Seems too much links

**Comment by jwasham** [comment]
I agree.

**Comment by jwasham** [comment]
I recently removed a bunch of dead links manually that from the report. I had to remove them from all translations.

**Comment by tianheg** [comment]
Here is my report about `README.md`: [link](https://github.com/tianheg/coding-interview-university/issues/1)

**Pull request merged**
