### PR TITLE
Translation:  French #chunk4

### PR DESCRIPTION
**Pull request by armandfardeau**
@amoulkaf 
Thanks for your initiative, i've done some work here. If it please you i would do more
https://github.com/amoulkaf/google-interview-university/issues/4

### CODE REVIEW

**Review by afsaneh751 — APPROVED** [review]

**Review by Iminathi1 — APPROVED** [review]

**Comment by armandfardeau** [comment]
Hi, @afsaneh751 and @Iminathi1 Thanks for the review!

**Comment by afsaneh751** [comment]
Please, I Need Help with Trustworthy, i Can not find me.

**Comment by afsaneh751** [comment]
Where are you from? If you have an email address that I can send a direct message to, thank you

**Review by afsaneh751 — APPROVED** [review]
[]()

**Comment by jwasham** [comment]
Thanks!

**Review by afsaneh751 — APPROVED** [review]
[]()

**Pull request merged**
