### PR TITLE
pt-br translation init

### PR DESCRIPTION
**Pull request by avizmarlon**
Started the translation to pt-br (Brazilian Portuguese). Added readme file to translations dir and did some initial translation.

Issue #113

### CODE REVIEW

**Comment by jwasham** [comment]
Let me know when you're ready for me to pull. thanks @avizmarlon

**Comment by jwasham** [comment]
When you're ready for me to pull, let me know.

**Comment by avizmarlon** [comment]
I'm working on the translation as I can, not much free-time lately. I will update you here when I finish it.

**Comment by jwasham** [comment]
No worries. Take your time. It's appreciated.

**Comment by marceloogeda** [comment]
@avizmarlon I can help you to translate it.

**Comment by avizmarlon** [comment]
@jwasham Its finished. I already edited readme.md to point to the translated file in /translations.

🍰

**Comment by avizmarlon** [comment]
@jwasham Hey, the translation is done.

**Comment by jwasham** [comment]
Thank you very much!

**Comment by avizmarlon** [comment]
You're welcome!

Closed issue #113

**Pull request merged**
