### PR TITLE
Kazakh translations

### PR DESCRIPTION
**Pull request by datbayev**
Initial readme for Kazakh translation

### CODE REVIEW

**Comment by jwasham** [comment]
Thank you @datbayev 
When you're ready for me to pull the translation, let me know.

**Review by skydiver1980 — APPROVED** [review]

**Comment by abhijeetsatpute** [comment]
@datbayev merge this
https://github.com/chettam/coding-interview-university/pull/1

**Comment by jwasham** [comment]
You'll need to push here. It's on your fork.

**Comment by abhijeetsatpute** [comment]
Don't have the write access on chettam:main

**Comment by abhijeetsatpute** [comment]
@jwasham See if this can be merged
https://github.com/jwasham/coding-interview-university/pull/1456

You can close 
https://github.com/jwasham/coding-interview-university/pull/1231
https://github.com/jwasham/coding-interview-university/pull/1084

**Pull request merged**
