### PR TITLE
Add vietnamese translation

### PR DESCRIPTION
**Pull request by letientai299**
Changes on `README.md`
----------------------------------

- Remove trailing whitespaces (my editor is setup for auto that).
- Add link to the vietnamese work

About Vietnamese translation.
---------------------------------------

- Complete until _Pick one language for the interview_.
- Add some note for later vietnamese contributors.
- _How to use it_ section is rewrote. I assume that you (@jwasham) write that section for people who don't know about git and GFM. So I direct them to other vietnamese guides. If you don't like this change, I will revert it :)

### CODE REVIEW

**Comment by jwasham** [comment]
About "how to use it" That's fine. Thank you!

Let me know when you're done and I'll pull.

**Comment by thovo** [comment]
@letientai299 May I join with you to finish the translation?

**Comment by letientai299** [comment]
Sure.

**Comment by jwasham** [comment]
Please move your translation file to the translations directory. Thank you!

**Comment by thovo** [comment]
I think we need to remove our change in 2 other files to prevent the conflict, I removed it before made a pull request to your repository but I think you merged also my previous commit.

**Comment by letientai299** [comment]
@thovo Don't worry. When we done the translation, he properly have more update to the original, so there will be conflicts anyway :smile:. We will resolve them all at once.

**Comment by jwasham** [comment]
When you're ready for me to pull, let me know.

**Comment by letientai299** [comment]
Hi @jwasham, Vietnamese translation is ready to merge.

**Comment by jwasham** [comment]
Before I merge, can you revert the change to the Hindi file? I don't know why that one was changed.

**Comment by letientai299** [comment]
My mistake. Fixed. Please review again.

**Comment by jwasham** [comment]
Thank you for the translation!

**Pull request merged**
