### PR TITLE
By syed Dayim shah

### PR DESCRIPTION
**Pull request by syedDayim**

### CODE REVIEW

**Comment by syedDayim** [comment]
Isn't this a good idea?

**Comment by syedDayim** [comment]
The reason for making a coding section of implementing data structures is to give people everything they need here in this repo.
the clean and easy code.

**Comment by syedDayim** [comment]
I was hoping to add more data structures in various languages.

**Comment by jwasham** [comment]
I appreciate the contribution, but I'd rather not have code samples here. There are plenty of resources available, including books and examples around the web.

**Pull request closed without merging**
