### PR TITLE
Add some Arabic translation

### PR DESCRIPTION
**Pull request by medaminefh**
#### Q: do anyone know how to link to different sections ? (In ar)

### CODE REVIEW

**Comment by jwasham** [comment]
I don't know if it's different in Arabic, but if you see a heading such as 
## ما هذا؟
the link would be [ما هذا؟](# ما هذا؟)

**Comment by medaminefh** [comment]
Actually its not working.
when that link is clicked nothing happens .
I did some researches, but i can't find the solu for this.
I think we need to add an id to the Header and accessed like that .

## <p id="what-is-this"> ما هذا؟</p>

## [ما هذا ؟](#what-is-this)

I don't know if there is a better way for that.

**Comment by medaminefh** [comment]
I kinda solved it in #968

**Comment by jwasham** [comment]
So discard this one and pull the other one?

**Comment by medaminefh** [comment]
Yes, and I'll try to keep translating this Amazing ressource ❤

**Pull request closed without merging**
