### PR TITLE
Add github workflow to check links and open issues reporting them

### PR DESCRIPTION
**Pull request by micalevisk**
My first attempt on use https://github.com/lycheeverse/lychee-action to automatically create an issue reporting all bad links. Here's an example of that issue: https://github.com/micalevisk/coding-interview-university/issues/1 This issue will be created only if there's some bad link on `README.md` file or in any `.md` on `translations` dir

Besides that, this workflow will find the last open issue with the label 'report' and update it instead of creating a new one. Or will close it if there's no bad link found.

Not sure if you guys are looking for something like this, tho.

### CODE REVIEW

**Comment by jwasham** [comment]
Pretty cool. It looks like it needs to be slowed down a bit, it's getting throttled and causing 429s.

**Comment by micalevisk** [comment]
I didn't face this issue in my tests with GH Actions, tbh. Also, I don't believe we can do something as a users of `lychee` tool :/

Looks like they didn't fixed it yet: https://github.com/lycheeverse/lychee/issues/367

**Comment by micalevisk** [comment]
actually, I think we could use `--max-concurrency` (_maximum number of concurrent network requests_) option to circunvemt this, but I don't know which value will be good. The default is `128`

**Comment by jwasham** [comment]
Because this is hitting a lot of the same domains, try setting it to 5. It doesn't need to be fast, so if there's a delay of a minute or so before a PR comes in, that's ok.

**Comment by micalevisk** [comment]
this workflow was intended to run on a scheduled basis (once in a month). Do you think another one for open PRs is worth it? I'll need to figure out how can I run check only in the links added in the PR then _(actually I'm already look into this because I need this feat in another project)_

**Comment by jwasham** [comment]
Nope, you're right. i don't know why I was thinking that. Once a month is fine.

**Comment by jwasham** [comment]
Thank you! Looking forward to the results!

**Pull request merged**
