### PR TITLE
Add french translate

### PR DESCRIPTION
**Pull request by nvana**
Have questions for the interviewer Part
Once You've Got The Job Part

[Issue 89](
https://github.com/jwasham/coding-interview-university/issues/89)

### CODE REVIEW

**Comment by MichaelTSS** [comment]
Merci @nvana, simple question, tu as omis un lien Medium et raccourci quelques phrases, c'est volontaire ?

**Comment by nvana** [comment]
Hello @MichaelTSS, en fait j'ai repris le texte du [README.md](https://github.com/jwasham/coding-interview-university#have-questions-for-the-interviewer), il y a des phrases en moins.

**Comment by jwasham** [comment]
This is very old, and requires conflicts to be resolved before it can be merged. @nvana  how would you like to proceed?

**Review by skydiver1980 — APPROVED** [review]

**Comment by jwasham** [comment]
Closing due to age of this open pull request.

**Pull request closed without merging**
