### PR TITLE
Corrected and updated Japanese translation.

### PR DESCRIPTION
**Pull request by kamegoro**
## Summary

The Japanese translation was adjusted and updated due to differences from the README.
The scope of this update is large, so we plan to update it little by little.

Thank you for your cooperation.

### CODE REVIEW

**Comment by kamegoro** [comment]
There are many differences, but most of them are due to formatting and the updated sections are up to the Git operations section.

**Comment by jwasham** [comment]
Understood. Can you undo the formatting changes and leave the translation changes?

**Comment by kamegoro** [comment]
@jwasham 

Thank you for your comment.

We have removed the plastic surgery areas you specified.
We hope to update the README gradually in the future.

**Comment by jwasham** [comment]
Thank you!

**Pull request merged**
