### PR TITLE
Fix Japanese translation

### PR DESCRIPTION
**Pull request by shogohida**
Signed-off-by: Shogo Hida <shogo.hida@gmail.com>

I will add Japanese translations to recent content in English like the parts below and try to improve existing translations.

> I studied about 8-12 hours a day, for several months. This is my story: [Why I studied full-time for 8 months for a Google interview](https://medium.freecodecamp.org/why-i-studied-full-time-for-8-months-for-a-google-interview-cc662ce9bb13)
> 
> Please Note: You won't need to study as much as I did. I wasted a lot of time on things I didn't need to know. More info about that below. I'll help you get there without wasting your precious time.

**Additional changes**
- There were unnecessary spaces after some sentences and they were removed thanks to my Visual Studio Code settings

### CODE REVIEW

**Comment by jwasham** [comment]
Once you're done making changes, let me know and I'll review for the PR.

**Comment by shogohida** [comment]
@jwasham 
I already finished so please review this PR!

**Comment by jwasham** [comment]
Thank you very much!

**Comment by shogohida** [comment]
You're very welcome! It seems the Japanese version is not revised that often so I will make other changes when they are necessary

**Pull request merged**
