### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by doctown**

### CODE REVIEW

**Comment by HariAcharya80** [comment]
what's going on? I don't see no meaningful changes?

**Comment by giri-reddy161** [comment]
I didn't find the dictionary yet i will be back with meaningful changes

**Comment by doctown** [comment]
@HariAcharya80 This was an accident, I thought I was creating a PR on my forked project so that's why I closed it immediately.

**Comment by giri-reddy161** [comment]
No problem, I understand.

**Comment by giri-reddy161** [comment]
Yuhuuuuuuu anybody home

**Comment by giri-reddy161** [comment]
Joke for a day Give a man a match, and he’ll be warm for a few hours. Set
him on fire, and he will be warm for the rest of his life.

**Comment by giri-reddy161** [comment]
My therapist said time heals all wounds. So I stabbed her.

**Comment by giri-reddy161** [comment]
Son: Dad, if I told you I was gay, would you still love me?
Dad: Don’t be silly son, you were an accident. I never loved you in the
first place.

**Comment by HariAcharya80** [comment]
stop nonsense, is this a relaxing forum?

**Comment by giri-reddy161** [comment]
My grandfather said my generation relies too much on technology. So I
unplugged his life support.

**Comment by giri-reddy161** [comment]
Yeah it's 3 o clock in the morning what u want me to do

**Comment by giri-reddy161** [comment]
I couldn't cry just because my grandfather died it almost winter i might
get cold 🥶

**Pull request closed without merging**
