### PR TITLE
change site for new languages

### PR DESCRIPTION
**Pull request by JheremeiArciaga**

### CODE REVIEW

**Comment by jwasham** [comment]
I see these are personal changes and whitespace changes.

**Comment by msapple0338** [comment]
Hi
I am a full-stack developer with 7+ years of experience.
I am a very passionate developer and I am responsible, honest, and always provide 100% results. 
I try to always be in touch so that you can ask any questions about the project.
I meet all your requirements from your list for the right candidate.
I work with Angularjs React.js/Redux/Next.js, Sass,Spring Boot, Asp.net, MongDB, express.js more than 5 years.
I hope to work with you.

**Comment by Wan-YunPeng** [comment]
Hello, I got your message. If it is important, please call me or message me.(您好，您的信息我已收到，如果很重要，请电话或短信联系我。)

**Comment by msapple0338** [comment]
my skype name = live:.cid.32ab97dd7f8c6ba7
I`ll wait Wan-YunPeng in skype

**Comment by msapple0338** [comment]
my skype name  live:.cid.32ab97dd7f8c6ba7
I`ll wait Wan-YunPeng in skype

**Pull request closed without merging**
