### PR TITLE
Hebrew translation - continuing 

### PR DESCRIPTION
**Pull request by YanaBe**
1. Changing the location to the translation folder
2. Adding more translated content

### CODE REVIEW

**Comment by jwasham** [comment]
When you're ready for me to pull, let me know.

**Comment by LTDO** [comment]
Ok sure

**Comment by jwasham** [comment]
This is pretty old, and needs conflicts resolved before merging. @YanaBe what would you like to do?

**Comment by YanaBe** [comment]
Thanks,
I believe the content had changed, it's ok to discard

Thank you

чт, 29 июл. 2021 г. в 08:58, John Washam ***@***.***>:

**Pull request closed without merging**
