### PR TITLE
Translation: French (for links and infos)

### PR DESCRIPTION
**Pull request by vmfunc**
Drafting this for now, this is not complete

Contributes to issue #89 

State of this PR : 

- [x] Bitwise operations
- [x] Trees
- [x] Sorting
- [ ] Graphs
- [ ] Recursion
- [ ] OOP
- [ ] Design patterns
- [ ] Combinatorics to String searching & manipulations

### CODE REVIEW

**Review by skydiver1980 — APPROVED** [review]

**Comment by jwasham** [comment]
Do you plan to continue @vmfunc? This is a couple of years old now.

**Comment by vmfunc** [comment]
hey there :) whoa this has been a while lol, almost three years! I can surely work on finishing that PR yeah, might take me a bit of time because I own a company now haha, but yeah I can for sure continue that PR c:

**Comment by jwasham** [comment]
I see we have a pretty good French translation so far already:
https://github.com/jwasham/coding-interview-university/blob/main/translations/README-fr.md

Please don't feel obligated to finish this.

**Comment by realjck** [comment]
> I see we have a pretty good French translation so far already: https://github.com/jwasham/coding-interview-university/blob/main/translations/README-fr.md
> 
> Please don't feel obligated to finish this.

Hello, there seems to be a problem with the link you provide, because unfortunately it is only about 25% translated, and the translation produced is of poor quality.

**Comment by jwasham** [comment]
I see. If you want to improve it and complete it, I'd appreciate it, but again, please don't feel obligated.

**Comment by jwasham** [comment]
Closing due to age of this PR

**Pull request closed without merging**
