### PR TITLE
Improving the consistency of capitalization and punctuation

### PR DESCRIPTION
**Pull request by Drakkkath**
This is my first pull request, I would greatly appreciate any feedback given to this!

### CODE REVIEW

**Review by John-pix — CHANGES_REQUESTED** [review]
As far as I have noticed, there is several places where you removed full stops, where you shouldn't. For example in line 506, 895, 896, 897, 1151, 1711. You should probably put those full stops back

**Comment by Drakkkath** [comment]
Thank you for the feedback, I will get it done.

**Comment by Drakkkath** [comment]
Have I done what is asked? I am kind of overwhelmed by this new platform...

**Comment by jwasham** [comment]
I'll go ahead and merge this. It's more trouble for reviewers to review requests like these that are very minor changes, but there was a lot of effort put into this, so I'll accept it. Thanks, but I'd recommend future PRs have changes that are more useful.

**Comment by Drakkkath** [comment]
You're definitely right on that, I am sorry to have put you through this trouble. I am trying to familiarize with the whole process, maybe in the future I'll get to contribute in a more helpful way! Thank you

**Pull request merged**
