### PR TITLE
Helpful websites for Career Opportunities

### PR DESCRIPTION
**Pull request by SRX9**
Added list of platforms which is helpful in finding the perfect job, internship or any other information like salary for a specific role in a specific company and much more.

### CODE REVIEW

**Review by SRX9 — COMMENTED** [review]
Verified

**Comment by jwasham** [comment]
I've noticed most of your pull requests are from ayedot. Are you the author?

**Comment by SRX9** [comment]
I am a blogger on the Ayedot Platform. Have 2 accounts, one is Programming Related and the Second one is a career and engineering-related.

**Comment by jwasham** [comment]
Thank you, I'll add this but I'd prefer content not proposed by the author 😉

**Pull request merged**
