### PR TITLE
Marathi translation README-mr.md

### PR DESCRIPTION
**Pull request by abhijeetsatpute**
Starting the Marathi Translation for **#1002** & #1208(Duplicate)

- [x] Coding Interview University
- [x] What is it?
- [x] Table of Contents
- [x] Optional Extra Topics & Resources
- [x] Why use it?
- [x] How to use it
- [x] Don't feel you aren't smart enough
- [x] A Note About Video Resources
- [x] Choose a Programming Language
- [x] Books for Data Structures and Algorithms
- [x] Interview Prep Books
- [x] Don't Make My Mistakes
- [x] What you won't see covered
- [x] The Daily Plan
- [x] Coding Question Practice
- [x] Coding Problems
- [x] Let's Get Started
- [x] Algorithmic complexity / Big-O / Asymptotic analysis
- [x] Data Structures
- [x] More Knowledge
- [x] Trees
- [x] Sorting
- [x] Graphs
- [x] Even More Knowledge
- [x] Final Review
- [x] Update Your Resume
- [x] Interview Process & General Interview Prep
- [x] Be thinking of for when the interview comes
- [x] Have questions for the interviewer
- [x] Once You've Got The Job
- [x] Additional Books
- [x] System Design, Scalability, Data Handling
- [x] Additional Learning
- [x] Additional Detail on Some Subjects
- [x] Video Series
- [x] Computer Science Courses
- [x] Algorithms implementation
- [x] Papers
- [x] LICENSE

### CODE REVIEW

**Comment by abhijeetsatpute** [comment]
@jwasham This is done

**Comment by jwasham** [comment]
Thank you!

**Comment by abhijeetsatpute** [comment]
Forgot to add the reference in main README.md file for README-mr.md
You can add it

**Comment by jwasham** [comment]
Done. Thanks again!

**Pull request merged**
