### PR TITLE
Update some words and Adding in readme-hi.md

### PR DESCRIPTION
**Pull request by jitendra3109**
Woking #81 
Yes! please review.
It will take the time to complete.
Am I going right direction to translate?

### CODE REVIEW

**Comment by MrSourabh** [comment]
Hi before making further changes can you please check if sections you are translating are present in master readme.md file. There are many sections that are removed all together. 
I'm currently traveling and don't have access to my computer. 

Appreciate your help. I'll rebase my files with your PR. Feel free to continue changes. 

Again deeply appreciate your help.

**Comment by jsroyal** [comment]
>can you please check if sections you are translating are present in the master readme.md file.

Yes! it is in the master. 

Why would you remove?  >There are many sections that are removed all together.

As of now I translate form which is in the readme-hi.md
So yeah you can merge it and rebase you PR.

**Comment by jsroyal** [comment]
>can you please check if sections you are translating are present in the master readme.md file.

You are comparing with readme.md v/s readme-hi.md

As of I translate which only part of readme-hi.md.
so if have right then you can merge it and also rebase your file

why would you do this >There are many sections that are removed all together.

**Comment by jsroyal** [comment]
@MrSourabh Is there any update of this PR?

**Comment by dhruvdutt** [comment]
This seems like good to merge.  :+1: 
@SaurabhMhaisekar

**Comment by jwasham** [comment]
Please resolve conflicts and I'll merge.

**Comment by IamManchanda** [comment]
Need help guys? :)

**Comment by jsroyal** [comment]
@IamManchanda What kind of help do you need?
Is it regarding this PR?
Sorry, too late @jwasham Is it still conflicts?

**Comment by jwasham** [comment]
Still conflicts.

**Comment by jwasham** [comment]
This is very old, and requires conflicts to be resolved before it can be merged. @jitendra3109  how would you like to proceed?

**Review by 404Nikhil — APPROVED** [review]

**Comment by jwasham** [comment]
This is approved but there are conflicts due to age. Please resolve the conflicts and update the pull request.

**Review by skydiver1980 — APPROVED** [review]

**Comment by jwasham** [comment]
Closing due to age of this open pull request.

**Pull request closed without merging**
