### PR TITLE
Fixed missing links and translation errors

### PR DESCRIPTION
**Pull request by SumitKar01**
Missing links and translation error has been fixed

### CODE REVIEW

**Comment by jwasham** [comment]
Please fix any conflicts and I'll pull.

**Comment by SumitKar01** [comment]
Markdown syntaxes were fixed.  That's the reason for conflict.

**Comment by jwasham** [comment]
Conflicts still exist.

**Comment by SumitKar01** [comment]
Conflicts have been resolved

**Comment by jwasham** [comment]
Thank you for your contribution!

**Pull request merged**
