### PR TITLE
Updated MIT Links

### PR DESCRIPTION
**Pull request by Anri-Lombard**
MIT links updated where possible while (1) maintaining original context and content of videos, and (2) being more relevant with a fresher feel.

Quick question: I've got links to free versions of most of the books you recommend. I suppose it is unethical to add these links, but if my judgement is wrong in any way I'll be happy to send them through.

Another addition: I found doing LeetCode's "learn" series better than CTCI, do you think recommending that will be useful?

### CODE REVIEW

**Comment by jwasham** [comment]
Thank you!

For the free versions of books. I would only link to free versions provided by the publisher, and avoid scans and other copies. Thanks for offering, though!

For LeetCode vs CTCI, I still recommend CTCI as a review and for studying for the interview, but please provide some links and I'll take a look.

**Comment by Anri-Lombard** [comment]
It's a pleasure!

The learn series on LeetCode can be found here: https://leetcode.com/explore/learn/ 
Perhaps it is better as an addition to CTCI than a supplement as you mentioned :)

**Comment by Anri-Lombard** [comment]
It's a pleasure!

The learn series on LeetCode can be found here: https://leetcode.com/explore/learn/ 
Perhaps it is better as an addition to CTCI than a supplement as you mentioned :)

**Comment by jwasham** [comment]
Wow these are really great. I'll take a look and see how I can fit these in.

**Pull request merged**
