### PR TITLE
Added another challenge site

### PR DESCRIPTION
**Pull request by anmolp476**
AlgoExpert is also a pretty popular website for coding interview practice.

### CODE REVIEW

**Comment by jwasham** [comment]
This pull request is in Draft

**Comment by anmolp476** [comment]
> This pull request is in Draft

Oh, I apologize! I think I made a mistake somehow, how can I revert it? Sorry, I've just started learning how to contribute to open source on Github 😅.

**Comment by anmolp476** [comment]
I clicked on, "Ready for Review", I think that should work! Again, I'm sorry!!

**Comment by jwasham** [comment]
Thanks!

**Pull request merged**
