### PR TITLE
Improved Docs

### PR DESCRIPTION
**Pull request by codewith-Ashish**

### CODE REVIEW

**Review by John-pix — COMMENTED** [review]
These changes are not necessary. They are are creator-specific. This must be in the way the creator @jwasham wants it to be. It's ok whether or not, these changes are merged. 

But I personally **disapprove** these changes because merging this could result in loss of conrinuety of this repo

**Comment by justaaguy** [comment]
I think this is a part of __Hacktoberfest__ Spam PR. Should mark it as invalid or spam.

**Comment by jwasham** [comment]
This won't work for the project. Closing.

**Comment by spekulatius** [comment]
context https://blog.domenic.me/hacktoberfest/ @jwasham

**Pull request closed without merging**
