### PR TITLE
English "README.md" file to the Turkish version

### PR DESCRIPTION
**Pull request by kgnblg**
I translated the original English "README.md" file until the "Interview Process & General Interview Prep" section.

### CODE REVIEW

**Comment by jwasham** [comment]
I think pulling this request would rename the English readme to the Turkish version.

**Comment by emreagbal** [comment]
Thanks for translate.

**Comment by jwasham** [comment]
This is very old, and requires conflicts to be resolved before it can be merged. @kgnblg   how would you like to proceed?

**Comment by Chaitanyate** [comment]
Please unsubscribe me from your mailing list

**Comment by kgnblg** [comment]
I started to merge the changes and translating the new added content, until the point where I translated. @jwasham 

I'll drop a comment here, when I finish the merge into my local.

**Comment by kgnblg** [comment]
I merged the changes from main branch and translated some additional parts. The first ~1000 lines have been translated and now it seems there is no more conflicts. @jwasham can you review the PR?

**Comment by jwasham** [comment]
Thank you!

**Comment by oguztonyali** [comment]
Hi, I would like to help if process is still on going.

Merhaba, süreç devam ediyorsa yardımcı olmak isterim.

**Comment by dizzy8888** [comment]
Can you send me the file

**Pull request merged**
