### PR TITLE
Marked X

### PR DESCRIPTION
**Pull request by RaymondJSu**
Sorry for asking this rudiment question, but I'm trying to understand how to use this repo to track the progress, I marked an item as 'X' and then 
`git rebase jwasham/main`
`git push --set-upstream origin progress` 
`git push --force`
which created this personal progress pull request (PR). I'm confused if marking other items as 'X' in the future will create additional PRs, or if it only happens once.

Thanks for clarifying!

### CODE REVIEW

**Comment by jwasham** [comment]
I understand and I'm not so sure myself.

I feel like once you've forked the repo, you should be able to make commits and push to your fork without pushing them here.

At work we are always pushing to a repo, but for this kind of work where you're dealing with a personal fork that should not be merged into the main one, I think our instructions are wrong.

**Comment by RaymondJSu** [comment]
Thank you for your response.

So, I suppose instead of using `git rebase` to jwasham/main, we should simply push our changes directly to our forked repository. Do you think that makes more sense?

**Comment by jwasham** [comment]
Yes. I should update the instructions!

**Comment by jwasham** [comment]
Thanks for bringing this up. After doing some research, I've updated the instructions.

**Pull request closed without merging**
